window.DYNAMIC_SURVEYS_CONFIG = {
  endpointUrl: "",
  spreadsheetId: "1HwNt31ghi4eCpIWPA_uQ4rNxV2WSCu-l_IfEgoIT0NI",
  defaultLanguage: "es",
  fallbackSurveyId: "",
  texts: {
    es: {
      appBadge: "Encuestas dinámicas",
      language: "Idioma",
      surveyId: "Encuesta",
      surveyHint: "Cargada desde Google Sheets.",
      metaTitle: "Datos de registro",
      metaHelp: "Completa los datos antes de guardar la evaluación.",
      date: "Fecha",
      session: "Sesión",
      panelistCode: "Código del catador o ID",
      batch: "Producto o lote",
      sampleCode: "Código de muestra",
      notes: "Observaciones",
      instructions: "Instrucciones",
      evaluation: "Evaluación",
      save: "Guardar encuesta",
      reset: "Limpiar formulario",
      loading: "Cargando encuesta...",
      loadingError: "No se pudo cargar la encuesta.",
      saveSuccess: "Encuesta guardada correctamente.",
      saveError: "No se pudo guardar la encuesta.",
      missingEndpoint: "Falta configurar la URL del Apps Script.",
      noQuestions: "La encuesta no tiene preguntas configuradas.",
      fillMeta: "Completa los datos obligatorios.",
      surveyLoaded: "Encuesta cargada."
    },
    en: {
      appBadge: "Dynamic surveys",
      language: "Language",
      surveyId: "Survey",
      surveyHint: "Loaded from Google Sheets.",
      metaTitle: "Registration details",
      metaHelp: "Complete the details before saving the evaluation.",
      date: "Date",
      session: "Session",
      panelistCode: "Panelist code or ID",
      batch: "Product or batch",
      sampleCode: "Sample code",
      notes: "Notes",
      instructions: "Instructions",
      evaluation: "Evaluation",
      save: "Save survey",
      reset: "Reset form",
      loading: "Loading survey...",
      loadingError: "Survey could not be loaded.",
      saveSuccess: "Survey saved successfully.",
      saveError: "Survey could not be saved.",
      missingEndpoint: "Apps Script URL is not configured.",
      noQuestions: "The survey has no configured questions.",
      fillMeta: "Complete the required fields.",
      surveyLoaded: "Survey loaded."
    }
  }
};
