window.DYNAMIC_SURVEYS_CONFIG = {
  endpointUrl: "https://script.google.com/macros/s/AKfycbyUXQpI6aiUaO1FTVnEgRZ6YzJfCYH-rfRxM-r8x9Ni2C1jg97hWP-lg5cDT9pNbRg_/exec",
  spreadsheetId: "1HwNt31ghi4eCpIWPA_uQ4rNxV2WSCu-l_IfEgoIT0NI",
  defaultLanguage: "es",
  fallbackSurveyId: "",
  texts: {
    es: {
      appBadge: "Encuestas dinámicas",
      language: "Idioma",
      surveyId: "Encuesta",
      surveyHint: "Cargada desde Google Sheets.",
      metaTitle: "Datos de registro",
      metaHelp: "Completa los datos antes de guardar la evaluación.",
      date: "Fecha",
      session: "Sesión",
      panelistCode: "Código del catador o ID",
      batch: "Producto o lote",
      sampleCode: "Código de muestra",
      notes: "Observaciones",
      instructions: "Instrucciones",
      evaluation: "Evaluación",
      save: "Guardar encuesta",
      reset: "Limpiar formulario",
      loading: "Cargando encuesta...",
      loadingError: "No se pudo cargar la encuesta.",
      saveSuccess: "Encuesta guardada correctamente.",
      saveError: "No se pudo guardar la encuesta.",
      missingEndpoint: "Falta configurar la URL del Apps Script.",
      noQuestions: "La encuesta no tiene preguntas configuradas.",
      fillMeta: "Completa los datos obligatorios.",
      surveyLoaded: "Encuesta cargada.",
      rankingHelp: "Ordena las opciones de mayor a menor preferencia.",
      moveUp: "Subir",
      moveDown: "Bajar",
      moveUpShort: "Subir",
      moveDownShort: "Bajar"
    },
    en: {
      appBadge: "Dynamic surveys",
      language: "Language",
      surveyId: "Survey",
      surveyHint: "Loaded from Google Sheets.",
      metaTitle: "Registration details",
      metaHelp: "Complete the details before saving the evaluation.",
      date: "Date",
      session: "Session",
      panelistCode: "Panelist code or ID",
      batch: "Product or batch",
      sampleCode: "Sample code",
      notes: "Notes",
      instructions: "Instructions",
      evaluation: "Evaluation",
      save: "Save survey",
      reset: "Reset form",
      loading: "Loading survey...",
      loadingError: "Survey could not be loaded.",
      saveSuccess: "Survey saved successfully.",
      saveError: "Survey could not be saved.",
      missingEndpoint: "Apps Script URL is not configured.",
      noQuestions: "The survey has no configured questions.",
      fillMeta: "Complete the required fields.",
      surveyLoaded: "Survey loaded.",
      rankingHelp: "Order the options from highest to lowest preference.",
      moveUp: "Move up",
      moveDown: "Move down",
      moveUpShort: "Up",
      moveDownShort: "Down"
    }
  }
};
